### ISSUE TITLE
Create an API route for getting all Donors

### ISSUE THREAD

**Issue by hoodus321** [hack4impact-utk/mission-of-hope#22]
# Description
Create a GET all donors api endpoint that returns all of the donors from the database

# Technical details
- Create a function in `app/api/donors/route.ts` (if it does not exist, create it) that looks like `export async function GET () { ... }`
- call `const result: UserResponse = getDonors()`
- Return the result from the get donors function `return NextResponse.json(result, {status: 200})`
- The API should be able to return multiple status codes:
    - on success: 200
    - on Unknown: 500
    - worry about the others later
- Here is an example of what it should look like `src/app/api/donations/route.ts`

# Dependencies
- #23

**Comment by alay10** [comment]
Repeat issue
