### ISSUE TITLE
Issue 5: Acknowledgement Letters

### ISSUE THREAD

**Issue by hoodus321** [hack4impact-utk/mission-of-hope#5]
- Description: Generate monthly donor acknowledgment letters & end-of-year summaries letters that can be printed and mailed. Create a template for both of these letters and allow donor information (name, amount donated, time they've been donating) to be in the letters as well, and then have a "print" button to print out these letters to be shipped. Maybe also have it to where they can change up their letter templates but still have the '(fill in the blank)' for donor information.

- Technical Details:

- Dependencies: Issue 1

**Comment by alay10** [comment]
Changed or mind about how issues are going to work
