### ISSUE TITLE
Get Donor by Id

### ISSUE THREAD

**Issue by alay10** [hack4impact-utk/mission-of-hope#59]
# Description
Create a system to fetch a donor to the mongodb database. Also, create a Get donor api endpoint that returns all of the donor from the database.

# Technical Details
- make sure you have your .env.local setup from the vault warden

- In the file `src/server/actions/donors.ts` Create the function `export async function function getDonorById(): Promise<DonorResponse>`
- `await dbConnect()` to connect to the database
- call `await DonorSchema.findById()` to find a single donation items and populate the item field
- return what the find call returns
- `src/server/actions/donations.ts` for reference
- [Example from the LBP](https://github.com/hack4impact-utk/internal-applications/blob/main/apps/form-builder/src/server/actions/forms.ts)

---

- Create a function in `app/api/Donor/[donorId]/route.ts` (if it does not exist, create it) that looks like `export async function GET () { ... }`
- call `const result: DonorResponse = geDonorById()`
- Return the result from the getDonorById function `return NextResponse.json(result, {status: 200})`
- The API should be able to return multiple status codes:
    - on success: 200
    - on Unknown: 500
    - worry about the others later
- Here is an example of what it should look like [this](https://github.com/hack4impact-utk/compassion-ministries/blob/main/src/app/api/volunteers/%5BvolunteerId%5D/route.ts#L56)

# Dependencies
- None

**Comment by AlanKha** [comment]
Hello! I believe I was assigned this issue. Can you add me?
