### ISSUE TITLE
View Donation Page

### ISSUE THREAD

**Issue by alay10** [hack4impact-utk/mission-of-hope#64]
# Description
Create a page to view a list of donations from the database. Show the Donor, Date, Brief item list, and entry user. This should be organized into a table.

# Technical Details
- Create the file `src/app/donation/page.tsx` (and the directory if it does not exist)
- Create a  [table](https://mui.com/material-ui/react-table/) item using a mui and populate it with [Typography components ](https://mui.com/material-ui/react-typography/) and the elements of the donationItem/ list of items
- Attempt to base this off of the design documents found in the Figma labeled Donation History
- use this example Donation item and display it on the screen:
```
const exDonation = 
{
  "_id": {
    "$oid": "65ce84429aca7f652bd1fd4f"
  },
  "user": {
    "_id": {
    "$oid": "65ce84429aca7f652bd1fd27"
    },
    "lastName": "Doe",
    "firstName": "John",
    "email": "john.doe@example.com",
    "admin": true
  },
  "items": [
  {
    "_id": {
      "$oid": "65ce84429aca7f652bd1fd31"
    },
    "name": "ProductA",
    "category": "Electronics",
    "high": 499.99,
    "low": 399.99
  }
  ],
  "entryDate": "2024-01-31",
  "donor": {
    "_id": {
      "$oid": "65ce84429aca7f652bd1fd1d"
    },
    "lastName": "Doe",
    "firstName": "John",
    "email": "john.doe@example.com",
    "address": "123 Main Street"
  }
}
```

- Example in  `src/app/donationItem/page.tsx`

# Dependencies
- None

**Comment by devTy33** [comment]
Backend connection is included in this pull request
